# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeorefArApi
                                 A QGIS plugin
 Este plugin consume la API de Goeref-ar-api
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-27
        copyright            : (C) 2026 by Datos Argentina
        email                : datosargentina@sicyt.gob.ar
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeorefArApi class from file GeorefArApi.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .georef_ar_api import GeorefArApi
    return GeorefArApi(iface)
