# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeorefArApi
                                 A QGIS plugin
 Este plugin consume la API de Goeref-ar-api
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Datos Argentina
        email                : datosargentina@sicyt.gob.ar
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMenu
from qgis.PyQt.QtWidgets import QToolBar

from .logic.addresses_dialog import AddressesDialog
from .logic.nearby_establishments_dialog import NearbyEstablishmentsDialog
from .logic.reverse_geocoding_dialog import ReverseGeocodingDialog
from .logic.about_dialog import AboutDialog
from .logic.settings_dialog import SettingsDialog
from .logic.endpoint_dialog import EndpointDialog
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
import os.path

class GeorefQgisPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir, 'i18n', '{}.qm'.format(locale))
        if os.path.exists(locale_path):
            self.translator = QTranslator(QCoreApplication.instance())
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr('Georef Ar Api')

        self.dlg = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = True

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeorefQgisPlugin', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        icon_path = ':/plugins/georef_ar_api/icon.png'

        old_toolbar = self.iface.mainWindow().findChild(QToolBar, "GeorefArToolbar")
        if old_toolbar:
            self.iface.mainWindow().removeToolBar(old_toolbar)
            old_toolbar.deleteLater()

        # 1. Crear las acciones
        self.action_lists = QAction(
            QIcon(icon_path),
            self.tr('Listados'),
            self.iface.mainWindow()
        )
        self.action_lists.triggered.connect(self.lists_callback)

        self.action_addresses = QAction(
            QIcon(icon_path),
            self.tr('Addresses'),
            self.iface.mainWindow()
        )
        self.action_addresses.triggered.connect(self.addresses_callback)

        self.action_reverse_georef = QAction(
            QIcon(icon_path),
            self.tr('Georeferenciación inversa'),
            self.iface.mainWindow()
        )
        self.action_reverse_georef.triggered.connect(self.reverse_georef_callback)

        self.action_near_establishments = QAction(
            QIcon(icon_path),
            self.tr('Establecimientos cercanos'),
            self.iface.mainWindow()
        )
        self.action_near_establishments.triggered.connect(self.near_establishments_callback)

        self.action_settings = QAction(
            self.tr('Settings'),
            self.iface.mainWindow()
        )
        self.action_settings.triggered.connect(self.settings_callback)

        self.action_about = QAction(
            self.tr('About'),
            self.iface.mainWindow()
        )
        self.action_about.triggered.connect(self.about_callback)

        # 2. Obtener el menú de Complementos (Plugins) de QGIS
        plugins_menu = self.iface.pluginMenu()

        # 3. Buscar si ya existe el submenú de tu plugin o crearlo
        # Esto evita que se cree el menú repetido si recargas
        self.q_menu = None
        for action in plugins_menu.actions():
            if action.menu() and action.menu().title() == self.tr('Georef AR API'):
                self.q_menu = action.menu()
                break

        if not self.q_menu:
            # Si no existe, lo creamos y lo añadimos al menú de Complementos
            self.q_menu = QMenu(self.tr('Georef AR API'), plugins_menu)
            plugins_menu.addMenu(self.q_menu)

        # 4. Limpiar el menú antes de agregar (por si es una recarga)
        self.q_menu.clear()
        self.q_menu.setIcon(QIcon(icon_path))

        # 5. Agregar las acciones
        self.q_menu.addAction(self.action_lists)
        self.q_menu.addAction(self.action_addresses)
        self.q_menu.addAction(self.action_reverse_georef)
        self.q_menu.addAction(self.action_near_establishments)
        self.q_menu.addSeparator()
        self.q_menu.addAction(self.action_settings)
        self.q_menu.addAction(self.action_about)

        # 6. Iconos simultáneos en la barra de herramientas independiente
        # Creamos la barra de manera estándar mediante la interfaz oficial de QGIS
        self.toolbar = self.iface.addToolBar("Georef AR Toolbar")
        self.toolbar.setObjectName("GeorefArToolbar")

        # Agregamos las tres acciones directamente
        self.toolbar.addAction(self.action_lists)
        self.toolbar.addAction(self.action_addresses)
        self.toolbar.addAction(self.action_reverse_georef)
        self.toolbar.addAction(self.action_near_establishments)

        # Guardamos la referencia de las tres acciones para el ciclo de vida del plugin
        self.actions = [
            self.action_lists,
            self.action_addresses,
            self.action_reverse_georef,
            self.action_near_establishments,
            self.action_settings,
            self.action_about
        ]

    def unload(self):

        """Elimina de forma segura todos los componentes inyectados en la interfaz de QGIS."""
        # 1. Quitar el traductor de la memoria de Qt
        if hasattr(self, 'translator'):
            QCoreApplication.removeTranslator(self.translator)

        # 2. Quitar el menú completo de la barra superior de Complementos de QGIS
        if hasattr(self, 'q_menu') and self.q_menu:
            plugins_menu = self.iface.pluginMenu()
            plugins_menu.removeAction(self.q_menu.menuAction())
            self.q_menu = None

        # 3. Quitar físicamente tu barra de herramientas usando la API nativa de QGIS
        if hasattr(self, 'toolbar') and self.toolbar:
            import sip  # Importamos la librería de gestión de memoria de PyQt

            # Desanclamos formalmente la barra de la ventana de QGIS
            self.iface.mainWindow().removeToolBar(self.toolbar)

            # Forzamos la destrucción SÍNCRONA e INMEDIATA del objeto en C++
            sip.delete(self.toolbar)
            self.toolbar = None

    def lists_callback(self):
        self.dlg = EndpointDialog(self.iface)
        self.dlg.show()
        self.dlg.exec_()

    def addresses_callback(self):
        self.dlg = AddressesDialog(self.iface)
        self.dlg.show()
        self.dlg.exec_()

    def reverse_georef_callback(self):
        self.dlg = ReverseGeocodingDialog(self.iface)
        self.dlg.show()
        self.dlg.exec_()

    def near_establishments_callback(self):
        self.dlg = NearbyEstablishmentsDialog(self.iface)
        self.dlg.show()
        self.dlg.exec_()

    def settings_callback(self):
        self.dlg = SettingsDialog()
        self.dlg.show()
        self.dlg.exec_()

    def about_callback(self):
        self.dlg = AboutDialog(self.iface.mainWindow())
        self.dlg.exec_()
