# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeorefArApiDialog
                                 A QGIS plugin
 Este plugin consume la API de Goeref-ar-api
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Datos Argentina
        email                : datosargentina@sicyt.gob.ar
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import requests

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'georef_ar_api_dialog_base.ui'))


class GeorefArApiDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GeorefArApiDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # URL por defecto
        if not self.lineEdit_url_base.text():
            self.lineEdit_url_base.setText("https://apis.datos.gob.ar/georef/api")

        # Conexiones de eventos
        self.pushButton_refresh.clicked.connect(self.refresh_api_data)
        self.comboBox_provincias.currentIndexChanged.connect(self.load_department_names)

        # Carga inicial
        self.load_provinces_names()

    def get_url(self, endpoint):
        """Construye la URL completa dinámicamente"""
        base = self.lineEdit_url_base.text().strip().rstrip('/')
        return f"{base}/{endpoint}"

    def refresh_api_data(self):
        """Limpia los campos y reinicia la carga desde la nueva URL"""
        # Bloqueamos señales para evitar ejecuciones en cascada accidentales
        self.comboBox_provincias.blockSignals(True)
        self.comboBox_departamentos.blockSignals(True)

        # Limpiar selecciones y checkboxes
        self.comboBox_provincias.clear()
        self.comboBox_departamentos.clear()
        self.checkBox_provincias.setChecked(False)
        self.checkBox_departamentos.setChecked(False)

        self.comboBox_provincias.blockSignals(False)
        self.comboBox_departamentos.blockSignals(False)

        # Volver a cargar provincias con la URL actual
        self.load_provinces_names()

        # Feedback visual opcional
        print(f"Datos recargados desde: {self.lineEdit_url_base.text()}")

    def load_provinces_names(self):
        """Obtiene nombres de provincias para el ComboBox"""
        url = "https://apis.datos.gob.ar/georef/api/provincias?campos=id,nombre"
        try:
            response = requests.get(url)
            data = response.json()
            provincias = sorted(data['provincias'], key=lambda x: x['nombre'])

            self.comboBox_provincias.blockSignals(True)  # Evitar disparar cargar_departamentos mientras llenamos
            self.comboBox_provincias.clear()
            self.comboBox_provincias.addItem("Seleccione una provincia...", None)
            for prov in provincias:
                self.comboBox_provincias.addItem(prov['nombre'], prov['id'])
            self.comboBox_provincias.blockSignals(False)
        except Exception as e:
            print(f"Error provincias: {e}")

    def load_department_names(self):
        prov_id = self.comboBox_provincias.currentData()
        self.comboBox_departamentos.clear()

        if not prov_id:
            return

        url = self.get_url(f"departamentos?provincia={prov_id}&campos=id,nombre&max=500")
        try:
            response = requests.get(url)
            data = response.json()
            departamentos = sorted(data['departamentos'], key=lambda x: x['nombre'])

            self.comboBox_departamentos.addItem("Todos los departamentos", None)
            for depto in departamentos:
                self.comboBox_departamentos.addItem(depto['nombre'], depto['id'])
        except Exception as e:
            print(f"Error departamentos: {e}")