# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeorefArApi
                                 A QGIS plugin
 Este plugin consume la API de Goeref-ar-api
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Datos Argentina
        email                : datosargentina@sicyt.gob.ar
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMenu
from qgis.PyQt.QtWidgets import QToolBar

from .strings import MenuStrings
from .logic.geocoding_dialog import GeocodingDialog
from .logic.nearby_establishments_dialog import NearbyEstablishmentsDialog
from .logic.reverse_geocoding_dialog import ReverseGeocodingDialog
from .logic.about_dialog import AboutDialog
from .logic.settings_dialog import SettingsDialog
from .logic.endpoint_dialog import EndpointDialog
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
import os.path

class GeorefQgisPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir, 'i18n', '{}.qm'.format(locale))
        if os.path.exists(locale_path):
            self.translator = QTranslator(QCoreApplication.instance())
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr('Georef Ar Api')

        self.dlg = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = True

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeorefQgisPlugin', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def _create_dialog_callback(self, dialog_class, *args, **kwargs):
        def callback():
            self.dlg = dialog_class(*args, **kwargs)
            self.dlg.show()
            self.dlg.exec_()
        return callback

    def initGui(self):
        icon_path = ':/plugins/georef_ar_api/icon.png'

        old_toolbar = self.iface.mainWindow().findChild(QToolBar, "GeorefArToolbar")
        if old_toolbar:
            self.iface.mainWindow().removeToolBar(old_toolbar)
            old_toolbar.deleteLater()

        # Actions
        self.action_territorial_units = self.add_action(
            icon_path=':/plugins/georef_ar_api/icons/territorial_units.svg',
            text=self.tr(MenuStrings.TERRITORIAL_UNITS_QUERIES_MENU_TITLE),
            callback=self._create_dialog_callback(EndpointDialog, self.iface),
            add_to_menu=False,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )

        self.action_addresses = self.add_action(
            icon_path=':/plugins/georef_ar_api/icons/geocoding.svg',
            text=self.tr(MenuStrings.GEOCODING_TITLE),
            callback=self._create_dialog_callback(GeocodingDialog, self.iface),
            add_to_menu=False,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )

        self.action_reverse_geocoding = self.add_action(
            icon_path=':/plugins/georef_ar_api/icons/reverse_geocoding.svg',
            text=self.tr(MenuStrings.REVERSE_GEOCODING_TITLE),
            callback=self._create_dialog_callback(ReverseGeocodingDialog, self.iface),
            add_to_menu=False,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )

        self.action_nearby_establishments = self.add_action(
            icon_path=':/plugins/georef_ar_api/icons/nearby_establishments.svg',
            text=self.tr(MenuStrings.NEARBY_ESTABLISHMENT_TITLE),
            callback=self._create_dialog_callback(NearbyEstablishmentsDialog, self.iface),
            add_to_menu=False,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )

        self.action_settings = self.add_action(
            icon_path=':/plugins/georef_ar_api/icons/settings.svg',
            text=self.tr(MenuStrings.SETTINGS_TITLE),
            callback=self._create_dialog_callback(SettingsDialog, self.iface.mainWindow()),
            add_to_menu=False,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )

        self.action_about = self.add_action(
            icon_path='',
            text=self.tr(MenuStrings.ABOUT_TITLE),
            callback=self._create_dialog_callback(AboutDialog, self.iface.mainWindow()),
            add_to_menu=False,
            add_to_toolbar=False,
            parent=self.iface.mainWindow()
        )

        # Menu
        plugins_menu = self.iface.pluginMenu()
        self.q_menu = None
        for action in plugins_menu.actions():
            if action.menu() and action.menu().title() == self.tr('Georef AR API'):
                self.q_menu = action.menu()
                break

        if not self.q_menu:
            self.q_menu = QMenu(self.tr('Georef AR API'), plugins_menu)
            plugins_menu.addMenu(self.q_menu)

        self.q_menu.clear()
        self.q_menu.setIcon(QIcon(icon_path))

        self.q_menu.addAction(self.action_territorial_units)
        self.q_menu.addAction(self.action_addresses)
        self.q_menu.addAction(self.action_reverse_geocoding)
        self.q_menu.addAction(self.action_nearby_establishments)
        self.q_menu.addSeparator()
        self.q_menu.addAction(self.action_settings)
        self.q_menu.addAction(self.action_about)

        # Toolbar
        self.toolbar = self.iface.addToolBar("Georef AR Toolbar")
        self.toolbar.setObjectName("GeorefArToolbar")
        self.toolbar.addAction(self.action_territorial_units)
        self.toolbar.addAction(self.action_addresses)
        self.toolbar.addAction(self.action_reverse_geocoding)
        self.toolbar.addAction(self.action_nearby_establishments)

    def unload(self):
        """Elimina de forma segura todos los componentes inyectados en la interfaz de QGIS."""

        if hasattr(self, 'translator'):
            QCoreApplication.removeTranslator(self.translator)

        if hasattr(self, 'q_menu') and self.q_menu:
            plugins_menu = self.iface.pluginMenu()
            plugins_menu.removeAction(self.q_menu.menuAction())
            self.q_menu = None

        if hasattr(self, 'toolbar') and self.toolbar:
            import sip
            self.iface.mainWindow().removeToolBar(self.toolbar)
            sip.delete(self.toolbar)
            self.toolbar = None


